- gatsby-node.js
- src/components/pagination/index.jsx
Closes #55 
`/page/2`, etc. is used for non-first page.
> feat: Use page prefix for numbered index pages

- src/components/externalLink/index.jsx
- src/components/footer/index.jsx
- src/components/icons/index.jsx
- src/templates/repository/index.jsx
- src/templates/repository/index.scss
Closes #72 
The top link was easily skippable. Adding it to the bottom too (like the back button) makes it easier to be seen.
Also add a GitHub icon to use on the GitHub links
> feat: Display GitHub on the top and bottom of the repository page

- src/components/actions/index.jsx
- src/components/card/index.jsx
- src/components/card/index.scss
- src/components/externalLink/index.jsx
- src/components/siteTitle/index.jsx
- src/components/zoomableImage/index.jsx
- src/components/zoomableImage/index.scss
- src/hooks/useNavigation.js
Closes #79 
**What was done:**
Even though it is not as accessible as before, using the `a` tag as the card wrapper fixes its position when focused. The other option was to use javascript to guess the scroll value, and scroll back to that value.
To counter the loss of accessibility, an aria-label was added to the card link.
**Also in this PR (a bunch of accessibility stuff):**
* Aria labels on actions
* Aria labels on the zoomable image input
* Scroll to focused element **only** if it is not in viewport
* Remove alt tag on the main logo to improve the experience with a screen reader
* Fix prop types on the external link component
* Make zoomable image input full size (to improve position on focus)
> fix: Center card position on focus

- gatsby-node.esm.js
- seed/data.json
- src/components/card/index.jsx
- src/components/card/index.scss
- src/components/icons/index.jsx
- src/constants/actions.js
- src/templates/repositories/index.jsx
- src/templates/repository/index.jsx
- src/types/index.js
Closes #87 
At build time, the stargazers count of the last week gets computed and added on to the repository node.
When the count is positive (> 0), it is displayed below the stargazers count.
Also in this PR:
* Remove isRequired from top type definitions (isRequired is to be decided at component level)
* Format seed data
* Fix owner name in repository page
* Rename and reorder sort actions
* Update URLs for sort actions to be more readable
_Note_: The (very basic) trending algorithm is not final. I would like to take the number of total stars into account, and maybe the creation date too. Improving the algorithm will be worked on through
> feat: Add trending sort (new default)

- src/components/pagination/index.scss
This PR fixes alignment for the pagination component on a mobile.
The final look, displayed on the screenshot:
Fixes: #38
> centered pagination on mobile

- src/hooks/useNavigation.js
I couldn't test locally (I don't have docker/mongodb/etc installed) so I just modified the script on the live website and it seems to work fine. (Using chrome's **local overrides** feature, I just started using it it's pretty nice 👀)
Closes #148
> Fix cmd + up/down arrows navigation on mac

- gatsby-config.js
Hi @reobin 
I've inverted the robots.txt env variable. A new one is GATSBY_ENABLE_ROBOTS. 
By default robots disallowed. I didn't find vercel CI config in the repo, could you please set in PROD build GATSBY_ENABLE_ROBOTS=true, to enable robots.txt for production.
Thanks
> inverted robots.txt env variable

- src/components/actions/index.jsx
- src/components/actions/index.scss
- src/components/header/index.scss
- src/components/intro/index.scss
- src/components/layout/index.scss
- src/components/siteTitle/index.scss
- src/components/themeSwitch/index.scss
Resolve #134 
- Aligned the logo and theme switch in a row on mobile
- Decreased the size of some spacings on mobile
- Updated the filters to be a horizontal list with scroll on mobile, and added a small right box-shadow to be an indicator.
- Added an useEffect on the actions component, just to force a scroll when the page loads (for example if someone access directly the /oldest route/filter)
Proof:
Let me know if I miss something :)
> feat(header): revamp header on mobile

- src/style/mixins/index.scss
Disables hover styles on touch devices.
Closes #204
> fix: disable hover styles on touch devices

- package.json
- src/components/siteTitle/index.jsx
- src/components/themeSwitch/index.jsx
- src/html.jsx
Fixed the theme switch on the initial load when the theme is dark.
Closes #99 
1. Set theme to dark
2. Reload page
3. Notice it no longer takes 3 clicks to change theme
> fix: Fix unresponsive dark theme switch

- db/data.json
- src/components/themeSwitch/index.jsx
- src/constants/keys.js
- src/hooks/useEventListener.js
- src/hooks/useKeyboardShortcuts.js
- src/hooks/useNavigation.js
- src/hooks/useTogglePointerEvents.js
Adds a keyboard shortcut (`b`) to toggle the current theme.
Closes #231 
Test `b` out in all pages
> feat: Add keyboard shortcut to toggle theme

- gatsby-node.esm.js
- src/templates/repositories/index.jsx
Exclude archived repositories , testing it with the recent given seed, by rivisitating filter of queries and also by adding additional controls in javascript code.
Closes #270 
With the recent seed we could find out this repository having archived variable setted to true:
By adding some controls and expanding the filter options of queries with
(the option of not equal was chosen to allow the pages with archived variable setted to null to be also builded)
To verify if my changes works just browse between two pages and see how you cannot locate "Hypsteria" repository
(I also excluded the creation of path URL to archived repositories)
> Added the exclusion of archived repositories #270

- src/styles/global.scss
https://github.com/vimcolorschemes/vimcolorschemes/issues/407
remove outline css from code tag
> fix: Remove focus indicator on code blocks on iOS

- src/components/preview/index.tsx
- src/gatsby/preview.ts
During preview image generation, wait for colors to be loaded on to the template before taking a screenshot with puppeteer.
Closes #415 
1. set `GATSBY_ENABLE_GENERATE_PREVIEW_IMAGES` to `true` in `.env`
2. run `npm run build`
3. open the `./public/previews` directory
4. check out the generated images
> fix: Wait for colors to be loaded before generating preview image

- .github/workflows/e2e_tests.yml
- .github/workflows/unit_tests.yml
Do not run E2E on PRs, as for them to work, we need to open secrets to fork PRs, which is a security hole.
> test: Run E2E tests only on main branch pushes

- src/components/filters/index.scss
- src/components/filters/index.tsx
- src/components/icons/checkboxChecked/index.tsx
- src/components/icons/checkboxUnchecked/index.tsx
Display an actual icon for the filter radio button display.
The other visual was not ideal as it glitched on some browsers.
1. Start the app
2. Use the filter radio buttons
> feat: Update filter radio button display

- src/components/preview/index.tsx
- src/gatsby/preview.ts
- src/models/repository.ts
- src/templates/preview/index.scss
- src/templates/preview/index.tsx
Display all variations in a nice gallery in the SEO preview image
1. Set `GATSBY_ENABLE_GENERATE_PREVIEW_IMAGES` to `true` in `.env`
2. `npm run build`
3. See `public/previews` directory
> feat: Display all color scheme variations in preview image

- src/gatsby/node.ts
- src/templates/repositories/index.tsx
Hides neovim color schemes until the UI is ready to receive them
#727 #726
> feat: Temporarily hide neovim color schemes in queries

- src/components/meta/index.scss
- src/components/meta/index.tsx
- src/components/pill/index.scss
- src/components/pill/index.tsx
- src/components/preview/index.scss
- src/components/preview/index.tsx
- src/gatsby/node.ts
- src/models/api.ts
- src/models/repository.ts
- src/models/vimColorScheme.ts
- src/styles/variables.scss
- src/templates/preview/index.tsx
- src/templates/repositories/index.tsx
- src/templates/repository/index.tsx
Based on data from the mongo database, add a "pill" on the bottom right of the repo card to display if the color scheme is lua or vim based.
Closes #727
> feat: Add visual cue for vim vs. lua color schemes

- src/gatsby/node.ts
- src/templates/repositories/index.tsx
🎉
Remove all filters for neovim color schemes.
Note: only most recently updated neovim color schemes will appear. Some older color schemes will take some time to appear on the website.
> feat: Display neovim (lua) color schemes

- src/components/preview/vimRC/index.tsx
For lua colorschemes, display `init.lua` code preview instead of a `.vimrc`
> feat: Add init.lua alternative for lua color schemes

- docs/install.md
Updates `install.md` to have instructions to `brew tap mongodb/brew` to install mongodb.
> fix: Update mongodb install instructions

- package-lock.json
- package.json
- src/helpers/s3.ts
- src/hooks/__tests__/search.test.ts
From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.
This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).
```console
$ npx aws-sdk-js-codemod@0.28.2 -t v2-to-v3 src/**/*.ts
```
N/A
N/A
> chore: migrate AWS SDK for JavaScript v2 APIs to v3

- src/app/repositories/[owner]/[name]/page.tsx
- src/components/interactivePreview/index.tsx
- src/components/preview/colorschemeConfig/index.tsx
- src/components/preview/index.tsx
- src/components/preview/windowHeader/index.tsx
- src/components/repositoryCard/index.tsx
- src/models/DTO/repository.ts
- src/models/colorscheme.ts
- src/models/repository.ts
* Flattens all repository colorscheme into non-interactive previews, and lists them all.
> feat: Add list of colorscheme variations in repository page
