vimcolorschemes/vimcolorschemes

- src/components/seo.jsx
> fix: Add site platform to the site title

- src/components/card/index.jsx
- src/components/repositoryTitle/index.jsx
- src/templates/repository/index.jsx
> fix: Use span instead of div inside of repository card link

- src/templates/repository/index.jsx
> feat: Use repository's description as page meta description

- gatsby-node.esm.js
- package-lock.json
- package.json
- src/components/card/index.jsx
- src/templates/repositories/index.jsx
- src/utils/date.js
Closes #92 
Uses dayjs to format dates on the client side
> fix: Format dates at runtime

- src/constants/actions.js
Thanks, vimcolorschemes for making vim color schemes easily accessible.
Fixes: #149
> Updated feed routes to have consistent naming

- README.md
- package-lock.json
- package.json
Hi @reobin,
Although `husky v5` is released, that one was still in alpha stage.
So I choose to use a combo of `husky v4` and `lint-staged` which suits perfectly for our requirement.
It was a great time playing with husky, Thanks😄
fixes: #169
> Dev: Husky - prettier format on pre-commit

- src/pages/about/index.jsx
fixes #147. Hey, I have added a basic plane section have a look at it and if I didn't get something wrong, review and provide feedback I will make it better and informative.
Why we are not allowing dotfiles? I could write a better statement if I know the reason, I guess it could include some personal .vimrc files.
Here's a screenshot of how it looks currently.
> added basic section regarding repo fetching on about page fix #147

- src/components/zoomableImage/index.scss
- src/style/mixins/index.scss
> #145 - Fix hover on image

- gatsby-node.esm.js
- package-lock.json
- package.json
- src/templates/repository/index.jsx
- src/utils/string.js
Hi @reobin 
I've added an emoji parser for the description, but not every emoji can be parsed with 'emoji-js' lib.
For example: :antarctica: is not recognized by emoji-js and parsed.
You can check it using the https://unicodey.com/js-emoji/demo/demo.htm.
Tried to find a replacement for emoji-js, but no luck. Could you please suggest any ideas on it?
Fixes: #96
> added emoji support for description

- src/components/repositoryTitle/index.scss
> fix overflow x issue

- src/components/siteTitle/index.jsx
- src/hooks/useNavigation.js
https://github.com/reobin/vimcolorschemes/issues/60
> fix:focus the element with corresponsing id onclick if element has hash

- src/components/actions/index.scss
- src/components/siteTitle/index.jsx
- src/hooks/useNavigation.js
Fixes an issue where clicking on the footer link in the about page (or any non home page) would not return back to the home page.
> fix: Clear focus when main logo is clicked

- .github/workflows/tests.yml
- cypress.json
- cypress/integration/home_page_spec.js
- cypress/integration/theme_switch_spec.js
> test: Add theme switch E2E tests

- .github/workflows/tests.yml
- .gitignore
- Dockerfile
- cypress/integration/theme_switch_spec.js
- cypress/support/commands.js
- cypress/support/index.js
- package.json
- src/components/themeSwitch/index.jsx
Use better practices for waiting for stuff to load.
> test: Refactor theme switch E2E tests

- src/components/pagination/index.scss
- src/style/index.scss
Fixes conflicts with anchor tag css.
N/A
Check out link font sizes in about page and pagination
> fix: Update back about page title font size

- cypress/support/commands.js
- src/api/index.js
- src/api/repository.js
- src/hooks/useSearchRepositories.js
- src/templates/repositories/index.jsx
Removes infinite loading state when a search error happens, and displays a corresponding message
- Use the search feature in the stg environment.
> fix: Display error message on search error

- src/components/pagination/index.scss
- src/components/pagination/index.tsx
> Pagination Button Fix

- package-lock.json
- package.json
- src/gatsby/node.ts
- src/services/elasticSearch.ts
Makes necessary changes to support elasticsearch@8
Closes #567
> build(deps-dev): Bump @elastic/elasticsearch from 7.17.0 to 8.1.0

- src/templates/repositories/index.tsx
> feat(seo): Add light/dark labels to document title when a filter is applied

- src/__tests__/hooks/useEventListener.test.ts
- src/__tests__/hooks/useKeyboardShortcut.test.ts
- src/components/searchInput/index.tsx
- src/helpers/dom.ts
- src/hooks/useEventListener.ts
- src/hooks/useKeyboardShortcut.ts
* `/`: Focus on search input
* `Escape`: Focus out of the search input and launch search
> feat: Add keyboard shortcuts for search input

- src/app/[owner]/[name]/layout.tsx
- src/app/[owner]/[name]/page.tsx
- src/app/about/layout.tsx
- src/app/about/page.tsx
- src/app/i/[...filters]/page.tsx
- src/components/ui/header/index.tsx
* Also refactor Header component to reduce specificity
> refactor: Use page layout for header

- src/app/(repository)/[owner]/[name]/layout.module.css
- src/app/(repository)/[owner]/[name]/layout.tsx
- src/app/(repository)/[owner]/[name]/not-found.module.css
- src/app/(repository)/[owner]/[name]/not-found.tsx
- src/app/(repository)/[owner]/[name]/page.tsx
[docs](https://nextjs.org/docs/app/api-reference/functions/not-found)
> refactor: Use notFound function for 404 repo page

- package.json
- pnpm-lock.yaml
> build(deps): Upgrade all dependencies to latest
